
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "M:/CMake/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:17 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
...
